spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 8323
  jpa:
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15m
    refreshTokenExpiration: 604800 #7d

  mail:
    host: smtp.gmail.com
    port: 587
    username: alirza.mehrzad@gmail.com
    password: ocpyutagbtfyvmvy   # Paste your 16-letter App Password here (no spaces)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true